### ISSUE TITLE
Making the docs on a fresh install errors out

### ISSUE THREAD

**Issue by ehsteve** [sunpy/package-template#11]
Here is the error

```
make html
Running Sphinx v2.4.4

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/sdchris1/anaconda3/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/sdchris1/anaconda3/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/Users/sdchris1/Developer/repositories/solar_datasets/docs/conf.py", line 106, in <module>
    target_file = os.path.abspath("./whatsnew/latest_changelog.txt")
NameError: name 'os' is not defined

make: *** [html] Error 2
(base) 
```
Adding the `import os` back at the top of the file solves this problem. Is this a bug?

**Comment by nabobalis** [comment]
Yes, the import is missing in the base file.

**Comment by nabobalis** [comment]
This was fixed?
